spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
#Use some git repo for prod configuration
#        git:
#          uri: ${HOME}/projects/config-repo

  profiles:
     active: native

  security:
    user:
      password: ${CONFIG_SERVICE_PASSWORD}