spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
#       TODO: add config for prod: git repo URL.
  profiles:
     active: native
  security:
    user:
      password: ${CONFIG_SERVICE_PASSWORD}