version: '2.1'

services:
  config:
    build: config
    image: turukin/d-echo-config
    ports:
      - 8888:8888

  eureka:
    build: discovery-service
    image: turukin/d-echo-eureka
    ports:
      - 8761:8761

  echo:
    build: echo-service
    image: turukin/d-echo-echo
    ports:
      - 8778:8778

  gateway:
    build: gateway
    image: turukin/d-echo-gateway
    ports:
      - 4000:4000