eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

logging.level:
  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN

management:
  endpoints.web.exposure.include: "info, health, refresh"
  info.git.mode: simple

echo.auth:
  cookie.name: D-ECHO-AUTH
  http.header.name: Authorization
