zuul:
  ignoredServices: '*'

  routes:
    echo-service:
      path: /echos/**
      serviceId: echo-service
      sensitiveHeaders:

    auth-service:
      path: /auth/**
      serviceId: auth-service
      sensitiveHeaders:


hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 20000

eureka.client.fetchRegistry: true

management.endpoints.web.exposure.include: "info, health, refresh, routes"